

export const ServerMessageActions = {
    CONNECT: "CONNECT",
    ROOM_UPDATE: "ROOM_UPDATE",
    PLAYER_UPDATE: "PLAYER_UPDATE",
    ROOM_UPDATE_LEAVE: "ROOM_UPDATE_LEAVE",
    ERROR: "ERROR",
    EQUIPMENT_INPUT: "EQUIPMENT_INPUT"
}